In [2]:
# TO - DO - Task
# 4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
# Problem - 1: Array Creation:

In [3]:
# 1. Initialize an empty array with size 2X2.
import numpy as np
empty=np.zeros((2,2))
empty

array([[0., 0.],
       [0., 0.]])

In [4]:
# 2. Initialize an all one array with size 4X2.
all_ones=np.ones((4,2))
all_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full=np.full((3,2),fill_value=7,dtype=int)
full

array([[7, 7],
       [7, 7],
       [7, 7]])

In [6]:
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
np.zeros_like((full),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [7]:
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
np.ones_like((full),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [8]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

In [9]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [10]:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 4. Create a random array of size 30 and find the mean of the array.
random=np.random.random(30)
random.mean()

np.float64(0.42735751960934987)

In [14]:
# Create a 10X10 array with random values and find the minimum and maximum values.
a=np.random.random((10,10))
print("Array:\n",a)
print("\n\nMinimum Value:",a.min())
print("Maximum Value:",a.max())



Array:
 [[0.85588421 0.53843189 0.15548253 0.77666147 0.24556172 0.91879528
  0.17129519 0.66768915 0.48815624 0.95348398]
 [0.72573299 0.84071488 0.25417163 0.77495775 0.67855703 0.54017236
  0.72561269 0.14390554 0.38008574 0.49016449]
 [0.35222454 0.21876009 0.39586411 0.12957208 0.86933759 0.19232825
  0.48492188 0.98683361 0.58456299 0.28894364]
 [0.84561757 0.7682379  0.81106018 0.53447315 0.53604772 0.91153626
  0.64301416 0.62974828 0.32613697 0.58323602]
 [0.9517296  0.65072682 0.59878933 0.52829681 0.58367564 0.01804023
  0.5519504  0.35843142 0.42281799 0.5223306 ]
 [0.31584658 0.07411147 0.16591686 0.57875612 0.58443528 0.18177088
  0.64803077 0.20445059 0.44030393 0.73460549]
 [0.67608832 0.5239464  0.13368785 0.07269802 0.23406131 0.97618926
  0.74378977 0.90645201 0.66663098 0.52584717]
 [0.01330589 0.63480249 0.42740811 0.36047607 0.08404974 0.27640162
  0.31959146 0.91281744 0.28258174 0.61263914]
 [0.3400689  0.87676865 0.79798241 0.96217648 0.59262741 0.92762319
  0.

In [15]:
# 6. Create a zero array of size 10 and replace 5th element with 1.
array=np.zeros(10)
array[4]=1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [16]:
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
arr.reverse()
arr

[0, 4, 0, 0, 2, 1]

In [17]:
# 8. Create a 2d array with 1 on border and 0 inside.
arr=np.ones((5,5),dtype=int)
arr[1:-1, 1:-1]=0
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [18]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
# Problem - 3: Array Operations:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])

In [37]:
# Complete all the task using numpy:
#1.Add the two array.
print("Addition:\n",x+y)

#2.Subtract the two array.
print("\nSubtraction:\n",x-y)

#3.Multiply the \Narray with any integers of your choice.
print("\nMultiplication:\n",3*x)

#4.Find the square of each element of the array.
print("\nSquare:\n",x**2)

#5.Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("\nDot(v,w):\n",np.dot(v,w))
print("\nDot(x,v):\n",np.dot(x,v))
print("\nDot(x,y):\n",np.dot(x,y))

#6.Concatenate x(and)y along row and Concatenate v(and)w along column.
print("\nConcat(x,y)row:\n",np.concatenate((x,y),axis=0))
print("\nConcat(v,w)col:\n",np.column_stack((v,w)))

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiplication:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot(v,w):
 219

Dot(x,v):
 [29 77]

Dot(x,y):
 [[19 22]
 [50 58]]

Concat(x,y)row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concat(v,w)col:
 [[ 9 11]
 [10 12]]


In [21]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print(np.concatenate((x,v)))
# We get the array because we are trying to concatenate arrays with different dimentions, which raises a value error. Concatinaion can only be done between arrays of same dimention.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
# Problem - 4: Matrix Operations:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
print("A.A_inv =\n",np.dot(A,np.linalg.inv(A)))
# A.A_inv=identity matrix proved.

A.A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [39]:
# 2. Prove AB ̸= BA.
print("AB =\n",np.dot(A,B))
print("BA =\n",np.dot(B,A))
# AB !=BA proved.

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [38]:
# 3. Prove (AB)T = BTAT
print("(AB)^T =\n",np.dot(A,B).T)
print("B^T.A^T =\n",np.dot(B.T,A.T))
# (AB)T = BTAT proved.

(AB)^T =
 [[23 51]
 [13 29]]
B^T.A^T =
 [[23 51]
 [13 29]]


In [25]:
# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A2=np.array([[2,-3,1],
             [1,-1,2],
             [3,1,-1]])
B2=np.array([-1,-3,9])

X2=np.linalg.solve(A2,B2)
print("\nUsing linalg.solve function: ",X2)

#Solve using np.linalg.inv function
X=np.dot(np.linalg.inv(A2),B2)
print("\nUsing linalg.inv function: ",X)


Using linalg.solve function:  [ 2.  1. -2.]

Using linalg.inv function:  [ 2.  1. -2.]
